name: Python Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install binary dependencies
        run: apt update && apt install -y git bzr fossil mercurial subversion
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install Python dependencies
        run: python -m pip install -r requirements-dev.txt

      - name: Run Python Tests
        run: python -m pytest --junitxml=test-results.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'test-results.xml'
